version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/meta"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/theme"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
