name: test

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - run: yarn install
      - run: yarn run test
